-- Library
local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RobloxScripts/main/Kavo%20UI%20Draggable%20Android.lua?token=GHSAT0AAAAAACGNMMWVOASIOPXUG5BI6MS6ZG6DKMQ"))()
local Window = Library.CreateLib("Important SCRIPTS Hub", "Ocean")

-- Main
local MainTab = Window:NewTab("Main")
local MainSec = MainTab:NewSection("Main Section")
local players = game:GetService("Players")
local localPlayer = players.LocalPlayer
local runService = game:GetService("RunService")

getgenv().thumbstick = false

local thumbstickFrame = localPlayer.PlayerGui.TouchGui.TouchControlFrame:FindFirstChild("ThumbstickFrame")

MainSec:NewButton("Infinite Yield", "", function() 
    loadstring(game:HttpGet("https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source"))()
end)
MainSec:NewButton("Turtle Spy", "", function()
    loadstring(game:HttpGet("https://pastebin.com/raw/BDhSQqUU", true))()
end)
MainSec:NewButton("Dark Dex V3", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Babyhamsta/RBLX_Scripts/main/Universal/BypassedDarkDexV3.lua", true))()
end)
MainSec:NewButton("Android Keyboard", "", function()
    loadstring(game:HttpGet("https://pastebin.com/raw/xSsDaMg2"))()
end)
MainSec:NewButton("Fly GUI V3", "", function()
    loadstring(game:HttpGet("https://pastebin.com/raw/gNb0mYab"))()
end)
MainSec:NewButton("P-Shade GUI", "", function()
    loadstring(game:HttpGet("https://pastefy.app/xXkUxA0P/raw"),true)()
end)
MainSec:NewButton("FPS Boost By RazerTexz", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RobloxScripts/main/FPS%20Boost%20By%20RazerTexz.lua?token=GHSAT0AAAAAACGNMMWUGWXEJD6JR4CG3X76ZG6DNRA"))()
end)
MainSec:NewButton("Walkspeed Gui", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RobloxScripts/main/Walkspeed%20Gui.lua?token=GHSAT0AAAAAACGNMMWUX4R35IVOA465ZYW6ZG6DQFA"))()
end)
MainSec:NewButton("Head Hitbox", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RobloxScripts/main/Head%20Hitbox.lua?token=GHSAT0AAAAAACGNMMWUVOZYYRY5ZDGKIR5KZG6DTEA"))()
end)
MainSec:NewButton("Hitbox", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RobloxScripts/main/Hitbox.lua?token=GHSAT0AAAAAACGNMMWUQQSLHULJA6Z5WWXOZG6DT7Q"))()
end)
MainSec:NewButton("Hide Gui", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RobloxScripts/main/Hide%20Gui.lua?token=GHSAT0AAAAAACGNMMWVRHIYK3ZNC3KUPHZQZG6DVFQ"))()
end)
MainSec:NewButton("R15 Invisibility Script", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RobloxScripts/main/R15%20Invisibility%20Script.lua?token=GHSAT0AAAAAACGNMMWVE6RUS4M7D7RQ5N6EZG6DVXA"))()
end)
MainSec:NewButton("Open Developer Console", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RobloxScripts/main/Open%20Developer%20Console.lua?token=GHSAT0AAAAAACGNMMWVP2MDIDZ4OXH755HIZG6DVXQ"))()
end)
MainSec:NewButton("RTX Gui By Sx-p0t", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RobloxScripts/main/RTX%20Gui%20By%20Sx-p0t.lua?token=GHSAT0AAAAAACGNMMWURW73LYRB2NFRJFVQZG6DVYQ"))()
end)
MainSec:NewButton("Change Thumbstick Position", "", function()
    thumbstick = not thumbstick
end)
MainSec:NewButton("Change Jump Button Position", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RobloxScripts/main/Change%20Jump%20Button%20Position.lua?token=GHSAT0AAAAAACGNMMWV3TMR6CM6Z764RZV6ZG6DLRA"))()
end)
MainSec:NewDropdown("Touch Movement Mode", "", {"UserChoice", "Thumbstick", "DPad", "Thumbpad", "Scriptable", "DynamicThumbstick"}, function(option)
    localPlayer.DevTouchMovementMode = Enum.DevTouchMovementMode[option]
end)

runService.Stepped:Connect(function()
    if thumbstick then
        thumbstickFrame.Position = UDim2.fromScale(0.09, 0.68)
    end
end)
