-- Library
local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RazerTexzRbScr/main/Kavo%20UI%20Draggable%20Android.lua"))()
local Window = Library.CreateLib("Important SCRIPTS Hub", "Ocean")

-- Main
local MainTab = Window:NewTab("Main")
local MainSec = MainTab:NewSection("Main Section")
local players = game:GetService("Players")
local localPlayer = players.LocalPlayer

MainSec:NewButton("Better Roblox V2", "", function() 
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RazerTexzRbScr/main/Better%20Roblox%20V2.lua"))()
end)
MainSec:NewButton("Change Thumbstick Position", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RazerTexzRbScr/main/Change%20Thumbstick%20Position.lua"))()
end)
MainSec:NewButton("Change Jump Button Position", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RazerTexzRbScr/main/Change%20Jump%20Button%20Position.lua"))()
end)
MainSec:NewButton("Chat Spy", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RazerTexzRbScr/main/Chat%20Spy.lua"))()
end)
MainSec:NewButton("Chat Spy GUI", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RazerTexzRbScr/main/Chat%20Spy%20GUI.lua"))()
end)
MainSec:NewButton("Dark Dex V3", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RazerTexzRbScr/main/Dark%20Dex%20V3.lua"))()
end)
MainSec:NewButton("Dark Dex V4", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RazerTexzRbScr/main/Dark%20Dex%20V4.lua"))()
end)
MainSec:NewButton("Fly GUI V3", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RazerTexzRbScr/main/Fly%20GUI%20V3.lua"))()
end)
MainSec:NewButton("FPS Boost By Infinite Yield", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RazerTexzRbScr/main/FPS%20Boost%20By%20Infinite%20Yield.lua"))()
end)
MainSec:NewButton("FPS Boost By RazerTexz", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RazerTexzRbScr/main/FPS%20Boost%20By%20RazerTexz.lua"))()
end)
MainSec:NewButton("Game Viewer", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RazerTexzRbScr/main/Game%20Viewer.lua"))()
end)
MainSec:NewButton("Head Hitbox", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RazerTexzRbScr/main/Head%20Hitbox.lua"))()
end)
MainSec:NewButton("Hide GUI", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RazerTexzRbScr/main/Hide%20GUI.lua"))()
end)
MainSec:NewButton("Hitbox GUI", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RazerTexzRbScr/main/Hitbox%20GUI.lua"))()
end)
MainSec:NewButton("Hitbox", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RazerTexzRbScr/main/Hitbox.lua"))()
end)
MainSec:NewButton("Hydroxide Remote Spy", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RazerTexzRbScr/main/Hydroxide%20Remote%20Spy.lua"))()
end)
MainSec:NewButton("Infinite Yield", "", function() 
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RazerTexzRbScr/main/Infinite%20Yield.lua"))()
end)
MainSec:NewButton("Keyboard Script", "", function() 
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RazerTexzRbScr/main/Keyboard%20Script.lua"))()
end)
MainSec:NewButton("P-Shade GUI", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RazerTexzRbScr/main/P-Shade%20GUI.lua"))()
end)
MainSec:NewButton("R15 Invisibility Script", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RazerTexzRbScr/main/R15%20Invisibility%20Script.lua"))()
end)
MainSec:NewButton("Simple Spy Mobile", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RazerTexzRbScr/main/Simple%20Spy%20Mobile.lua"))()
end)
MainSec:NewButton("Turtle Spy", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RazerTexzRbScr/main/Turtle%20Spy.lua"))()
end)
MainSec:NewButton("Walkspeed GUI", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RazerTexzRbScr/main/Walkspeed%20GUI.lua"))()
end)
MainSec:NewDropdown("Touch Movement Mode", "", {"UserChoice", "Thumbstick", "DPad", "Thumbpad", "Scriptable", "DynamicThumbstick"}, function(opt)
    localPlayer.DevTouchMovementMode = Enum.DevTouchMovementMode[opt]
end)