-- Library
local Library = loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RazerTexzRbScr/main/Kavo%20UI%20Draggable%20Android.lua"))()
local Window = Library.CreateLib("Important SCRIPTS Hub", "Ocean")

-- Main
local MainTab = Window:NewTab("Main")
local MainSec = MainTab:NewSection("Main Section")
local players = game:GetService("Players")
local localPlayer = players.LocalPlayer

MainSec:NewButton("Infinite Yield", "", function() 
    loadstring(game:HttpGet("https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source"))()
end)
MainSec:NewButton("Turtle Spy", "", function()
    loadstring(game:HttpGet("https://pastebin.com/raw/BDhSQqUU", true))()
end)
MainSec:NewButton("Dark Dex V3", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/Babyhamsta/RBLX_Scripts/main/Universal/BypassedDarkDexV3.lua", true))()
end)
MainSec:NewButton("Android Keyboard", "", function()
    loadstring(game:HttpGet("https://pastebin.com/raw/xSsDaMg2"))()
end)
MainSec:NewButton("Fly GUI V3", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RazerTexzRbScr/main/Fly%20GUI%20V3.lua"))()
end)
MainSec:NewButton("P-Shade GUI", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RazerTexzRbScr/main/P-Shade%20GUI.lua"))()
end)
MainSec:NewButton("FPS Boost By RazerTexz", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RazerTexzRbScr/main/FPS%20Boost%20By%20RazerTexz.lua"))()
end)
MainSec:NewButton("Walkspeed GUI", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RazerTexzRbScr/main/Walkspeed%20GUI.lua"))()
end)
MainSec:NewButton("Head Hitbox", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RazerTexzRbScr/main/Head%20Hitbox.lua"))()
end)
MainSec:NewButton("Hitbox", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RazerTexzRbScr/main/Hitbox.lua"))()
end)
MainSec:NewButton("Hide GUI", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RazerTexzRbScr/main/Hide%20GUI.lua"))()
end)
MainSec:NewButton("R15 Invisibility Script", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RazerTexzRbScr/main/R15%20Invisibility%20Script.lua"))()
end)
MainSec:NewButton("Open Developer Console", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RazerTexzRbScr/main/Open%20Developer%20Console.lua"))()
end)
MainSec:NewButton("RTX GUI By Sx-p0t", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RazerTexzRbScr/main/RTX%20GUI%20By%20Sx-p0t.lua"))()
end)
MainSec:NewButton("Change Thumbstick Position", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RazerTexzRbScr/main/Change%20Thumbstick%20Position.lua"))()
end)
MainSec:NewButton("Change Jump Button Position", "", function()
    loadstring(game:HttpGet("https://raw.githubusercontent.com/RazerTexz/RazerTexzRbScr/main/Change%20Jump%20Button%20Position.lua"))()
end)
MainSec:NewDropdown("Touch Movement Mode", "", {"UserChoice", "Thumbstick", "DPad", "Thumbpad", "Scriptable", "DynamicThumbstick"}, function(option)
    localPlayer.DevTouchMovementMode = Enum.DevTouchMovementMode[option]
end)